# Generated by Django 4.1.7 on 2023-04-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.CharField(default="default@email.com", max_length=200),
        ),
        migrations.AlterField(
            model_name="order",
            name="complete",
            field=models.BooleanField(default=False),
        ),
    ]
