# Generated by Django 4.2 on 2023-04-10 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0003_alter_customer_email_alter_order_complete"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="descrizione",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=42),
        ),
    ]
